### ISSUE TITLE
Generated sprite names on Windows

### ISSUE THREAD

**Issue by mikke89** [svenvvv/rcss-sprite-ed#16]
On Windows, the directory divider `\` remains in the sprite names after packing sprites. Eg. `resources\food` instead of `resources-food`.

**Comment by svenvvv** [comment]
Should be fixed by 2f1aea7.
I don't have any Windows boxes to test on, but it should work, as I don't think Windows ever hands out paths with unix separators.

**Comment by mikke89** [comment]
Yup, works for me! Thanks.
